"""R08: repair the existing flight shot's loss of city context.
Reuse the exact R07B finished ship, 20 km ring, buildings and render helpers.
No remodelling, no new ring, no replacement reference and no autogenerated art PASS.
Only ship/camera staging and the existing daylight rig change. The exterior shot
remains independently recoverable from its immutable input .blend and 1080p movie.
"""
import bpy,os,json,hashlib,math,ast,time,struct,resource
from pathlib import Path
from mathutils import Vector
from bpy_extras.object_utils import world_to_camera_view
ROOT=Path(__file__).resolve().parent;OUT=Path(os.environ['SKYFOLD_OUT']);OUT.mkdir(parents=True,exist_ok=True)
S=bpy.context.scene;BASE=Path(bpy.data.filepath);MODE=os.environ.get('R08_MODE','build')
def digest(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def matrix(o):return [list(r) for r in o.matrix_world]
def corners(o):return [o.matrix_world@Vector(v) for v in o.bound_box]
def savejson(name,data):(OUT/name).write_text(json.dumps(data,indent=2,ensure_ascii=False))
assert bpy.app.version[:3]==(4,5,13)
if MODE=='build':
 expected='e9ffbb9051f27fe6c19d6ff7069cd5f419b9517e3b4ee2b0d0f889845e8086c6';assert digest(BASE)==expected
 meta=json.loads(BASE.with_name('BUILD-MANIFEST.json').read_text());S.frame_set(1);bpy.context.view_layer.update()
 C={c.name:c for c in bpy.data.collections};ship=C['04_FREIGHTER'];root=bpy.data.objects['R06_SHIP_FORWARD_FLIGHT'];target=bpy.data.objects['R06_TRACKING_TARGET']
 # Read-only evidence from the actual loaded scene, before mutation.
 env=[o for o in S.objects if o.type in {'MESH','CURVE','FONT'} and o.name not in ship.objects]
 sig={o.name:matrix(o) for o in env};topology={o.name:(o.data.name,len(o.data.vertices),len(o.data.polygons)) for o in S.objects if o.type=='MESH'}
 savejson('RECON.json',{'input_sha256':expected,'blender':bpy.app.version_string,'collections':{k:len(v.objects) for k,v in C.items()},'ship_hull_bounds':[list(v) for v in corners(bpy.data.objects['Freighter tapered pressure hull'])],'ring_diameter_m':meta['R07_scale_change']['new_ring_diameter_m'],'reused_render_entry':'r06_flight.py / config','mutation_scope':'Ship root translation, new cameras, existing lighting and world only; no mesh changes','external_assets':[]})
 root.animation_data_clear();root.rotation_euler=(0,0,0);target.location=(150,120,600)
 cameras=[]
 for name,offset,lens in [('R08_CROSS_CITY',(-1500,-650,-180),20),('R08_CITY_QUARTER',(-1300,-1000,-250),22)]:
  d=bpy.data.cameras.new(name);d.lens=lens;d.sensor_width=36;d.clip_start=.2;d.clip_end=60000;d.dof.use_dof=False
  o=bpy.data.objects.new(name,d);C['08_CAMERAS'].objects.link(o);o.parent=root;o.location=offset
  c=o.constraints.new('TRACK_TO');c.target=target;c.track_axis='TRACK_NEGATIVE_Z';c.up_axis='UP_Y';cameras.append(o)
 for f in range(1,193):
  t=(f-1)/191;root.location=(-6000,3200-640*t,4400+20*t);root.keyframe_insert(data_path='location',frame=f)
 S.frame_start=1;S.frame_end=192;S.render.fps=24;S.camera=cameras[0]
 # Daylight fills the inhabited space; ship-only finishing materials are preserved.
 world=bpy.data.worlds.new('R08 inhabited daylight');world.use_nodes=True;nt=world.node_tree
 sky=nt.nodes.new('ShaderNodeTexSky');sky.sky_type='NISHITA';sky.sun_disc=False;sky.sun_elevation=.65;sky.sun_rotation=4.0;sky.dust_density=.35
 bg=nt.nodes.get('Background');bg.inputs['Strength'].default_value=.42;nt.links.new(sky.outputs['Color'],bg.inputs['Color']);S.world=world
 sun=bpy.data.objects['R07 soft directional daylight'];sun.data=sun.data.copy();sun.data.energy=2.6;sun.data.angle=.055;sun.data.color=(1,.90,.77)
 sun.rotation_euler=(Vector((-6000,3200,4500))-Vector((-4000,-9000,20000))).to_track_quat('-Z','Y').to_euler()
 for name,power in [('R07 large reflected sky aperture',16000000),('R07 lower reflected city fill',4000000),('R07B Finish / rear edge card',18000000)]:
  o=bpy.data.objects[name];o.data=o.data.copy();o.data.energy=power
 for n in S.node_tree.nodes:
  if n.bl_idname=='CompositorNodeMapRange':n.inputs['From Min'].default_value=2200;n.inputs['From Max'].default_value=24000;n.inputs['To Max'].default_value=.14
  elif n.bl_idname=='CompositorNodeMixRGB':n.inputs[2].default_value=(.30,.42,.54,1)
 S.view_settings.view_transform='AgX';S.view_settings.look='AgX - Medium High Contrast';S.view_settings.exposure=-.12
 checks=[];S.render.resolution_x=1280;S.render.resolution_y=720
 for f in [1,49,97,145,192]:
  S.frame_set(f);bpy.context.view_layer.update();pts=[p for o in ship.objects if o.type=='MESH' and not o.hide_render for p in corners(o)]
  assert max(math.hypot(p.x,p.z-10000) for p in pts)<9000
  assert min(p.y for p in pts)>1800
  for cam in cameras:
   uv=[world_to_camera_view(S,cam,p) for p in pts];bounds=[min(v.x for v in uv),max(v.x for v in uv),min(v.y for v in uv),max(v.y for v in uv)]
   assert all(v.z>0 for v in uv) and min(bounds)>-.05 and max(bounds)<1.05,(cam.name,bounds)
   camera_radius=math.hypot(cam.matrix_world.translation.x,cam.matrix_world.translation.z-10000);assert camera_radius<9600,camera_radius
   checks.append({'frame':f,'camera':cam.name,'ship_bbox_uv':bounds,'ship_matrix':matrix(root),'camera_matrix':matrix(cam),'camera_inside_shell_margin_m':10000-camera_radius})
 S.frame_set(1);bpy.context.view_layer.update()
 assert all(matrix(o)==sig[o.name] for o in env),'Environment geometry moved'
 assert all((o.data.name,len(o.data.vertices),len(o.data.polygons))==topology[o.name] for o in S.objects if o.type=='MESH'),'Unexpected geometry change'
 S['candidate']='R08_INHABITED_FORWARD_FLIGHT';S['source_sha']=os.environ['GITHUB_SHA'];S['auto_qualified']=False
 current={'candidate':S['candidate'],'source_sha':os.environ['GITHUB_SHA'],'parent_scene_sha256':expected,'blender':bpy.app.version_string,'scene_origin':'Current verified R07B finish; no geometry replacement','scope':'Explicit user forward-flight shot amendment. Core dock/transport acceptance not implied.','protected_exterior_movie_run':34559500985,'environment_transforms_unchanged':True,'mesh_datablocks_counts_unchanged':True,'motion':{'fps':24,'frames':192,'heading':'WORLD_NEGATIVE_Y','start':[-6000,3200,4400],'end':[-6000,2560,4420],'tracking':'TRACK_TO plus camera parented to the independent ship root','environment_stationary':True,'checks':checks},'old_camera_control':'Old exterior cameras are preserved in the immutable input scene. Do not call changed-parent cameras same-world-matrix regressions.','collision_scope':'Ship and camera bounds clear the ring shell and dock axial region; not all-object triangle collision proof','geometry_shader_sources':'All inherited and editable from the supplied parent scene','artistic_status':'NOT_REVIEWED','auto_qualified':False}
 p=OUT/'skyfold-r08.blend';bpy.ops.wm.save_as_mainfile(filepath=str(p),compress=True);current['scene_sha256']=digest(p);savejson('BUILD-MANIFEST.json',current);print('R08_SAVED',current['scene_sha256'],flush=True)
else:
 meta=json.loads(BASE.with_name('BUILD-MANIFEST.json').read_text());assert digest(BASE)==meta['scene_sha256']
 definitions=[n for n in ast.parse((ROOT/'r06_flight.py').read_text()).body if isinstance(n,ast.FunctionDef) and n.name=='config'];assert len(definitions)==1;exec(compile(ast.Module(body=definitions,type_ignores=[]),'EXISTING_R06_RENDER_CONFIG','exec'),globals())
 if MODE=='probe':views=[('R08_CROSS_CITY',1,1280,24,False,True),('R08_CITY_QUARTER',1,1280,24,False,True),('R08_CROSS_CITY',192,1280,24,False,True),('R08_CROSS_CITY',1,960,16,True,False)]
 elif MODE=='stills':views=[(os.environ.get('R08_CAMERA','R08_CROSS_CITY'),f,w,n,False,grade) for f,w,n,grade in [(1,2560,96,True),(97,1920,64,True),(192,1920,64,True),(1,1280,32,False)]]
 else:raise ValueError(MODE)
 rows=[]
 for name,f,w,n,neutral,grade in views:
  S.frame_set(f);S.camera=bpy.data.objects[name];bpy.context.view_layer.update();config(w,n,False);S.render.use_compositing=grade;S.view_layers[0].material_override=bpy.data.materials['Neutral inspection clay'] if neutral else None
  p=OUT/('%s_f%03d_%s.png'%(name,f,'NEUTRAL' if neutral else 'BEAUTY' if grade else 'RAW'));S.render.filepath=str(p)
  start=time.perf_counter();bpy.ops.render.render(write_still=True);elapsed=time.perf_counter()-start
  assert struct.unpack('>II',p.read_bytes()[16:24])==(w,w*9//16)
  rows.append({'file':p.name,'frame':f,'dimensions':[w,w*9//16],'samples':n,'neutral':neutral,'compositing':grade,'seconds':elapsed,'rss_peak_kib':resource.getrusage(resource.RUSAGE_SELF).ru_maxrss,'camera_matrix':matrix(S.camera),'ship_matrix':matrix(bpy.data.objects['R06_SHIP_FORWARD_FLIGHT']),'ring_matrix':matrix(bpy.data.objects['Continuous inhabited ring shell']),'scene_sha256':meta['scene_sha256'],'scene_source_sha':meta['source_sha'],'render_source_sha':os.environ['GITHUB_SHA'],'sha256':digest(p),'visual_verdict':'NOT_OBSERVED'})
  savejson('OBSERVATIONS.json',rows);print('R08_RENDERED',p.name,elapsed,flush=True)
 S.view_layers[0].material_override=None;savejson('COMPLETE.json',{'mode':MODE,'count':len(rows),'run_id':os.environ['GITHUB_RUN_ID'],'scene_sha256':meta['scene_sha256'],'auto_qualified':False})
