/** Actual UI checks. Local document injection is explicitly distinguished from HTTP cold start. */
import {chromium} from '@playwright/test';import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import crypto from 'node:crypto';
const out='evidence/R02';fs.mkdirSync(out,{recursive:true});
const local=process.env.CHIRON_LOCAL_DOCUMENT==='1',small=process.env.CHIRON_SMALL==='1',quick=process.env.CHIRON_QUICK==='1';
const manifest=JSON.parse(fs.readFileSync('dist/build-manifest.json'));const report={buildHash:manifest.buildHash,transport:local?'SANDBOX_DOCUMENT_INJECTION: navigation blocked by installed browser policy, not HTTP cold start':'HTTP_COLD_START',assurance:'SEQUENTIAL_SELF_REVIEW + actual Playwright input; software renderer; no mobile hardware',started:new Date().toISOString(),checks:[],shots:[],errors:[]};
function save(){fs.writeFileSync(out+'/browser-report.json',JSON.stringify(report,null,2));}
let server;if(!local){server=spawn(process.execPath,['tools/serve.mjs'],{stdio:'ignore'});await new Promise(r=>setTimeout(r,800));}
const options={headless:false,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']};if(process.env.CHROMIUM_PATH)options.executablePath=process.env.CHROMIUM_PATH;else if(fs.existsSync('/usr/bin/chromium'))options.executablePath='/usr/bin/chromium';
const browser=await chromium.launch(options);const context=await browser.newContext({viewport:small?{width:1100,height:800}:{width:1920,height:1080},deviceScaleFactor:1,recordVideo:{dir:out+'/video',size:small?{width:1100,height:800}:{width:1280,height:720}}});
const page=await context.newPage();page.setDefaultTimeout(40000);page.on('pageerror',e=>{report.errors.push(e.message);save();});
async function load(p=page){if(local)await p.setContent(fs.readFileSync('dist/Chiron-Sapphire-R02.html','utf8'));else await p.goto('http://127.0.0.1:4173',{waitUntil:'load'});await p.waitForFunction(()=>window.__chiron?.snapshot().state.ready,{},{timeout:60000});}
const snap=()=>page.evaluate(()=>window.__chiron.snapshot());
async function check(name,fn){console.log('BEGIN',name);try{await fn();report.checks.push({name,status:'PASS'});console.log('PASS',name);}catch(e){report.checks.push({name,status:'FAIL',error:e.message});console.error('FAIL',name,e.message);}save();}
async function shot(id){await page.waitForTimeout(600);const s=await snap();await page.screenshot({path:`${out}/${id}.png`,animations:'disabled'});report.shots.push({id,path:`${id}.png`,buildHash:manifest.buildHash,state:s.state,camera:s.camera,viewport:s.viewport,renderer:s.renderer,backend:s.runtime.backend});save();}
const click=q=>page.locator(q).click();
try{
await load();report.initial=await snap();save();
await check('O01 HTML, real 3D ready, seven chapters',async()=>{assert.equal(await page.locator('.chapter').count(),7);assert.equal((await snap()).state.ready,true);assert.equal((await snap()).runtime.errors.length,0);await shot('O01-hero');});
await check('O32 start and direct exploration',async()=>{await click('#the-object [data-do=start]');assert.equal((await snap()).state.starts,1);await click('#the-object [data-do=explore]');assert.equal((await snap()).state.mode,'explore');});
// Reduced motion is an explicit user operation, not a hidden test setter.
await click('#motion-toggle');
await check('O02-O04 actual UI front, back, left, right',async()=>{for(const view of ['front','back','left','right']){await click(`[data-view=${view}]`);await shot(`O0${view==='front'?2:view==='back'?3:4}-${view}`);}});
await check('O06 same watch with crystal digitally removed',async()=>{await click('[data-view=front]');await click('#crystal-control');assert.equal((await snap()).state.crystalOff,true);await shot('O06-crystal-off');await click('#crystal-control');});
await check('O08-O09 W16 isolated, sixteen real rendered endpoints',async()=>{await click('#dock [data-do=inspect-engine]');await click('#crown-toggle');await page.locator('#engine-rate').selectOption('0.1');await click('#crown-panel [data-do=windEngine]');await click('#dock [data-do=start]');await page.waitForTimeout(700);const a=await snap();await click('#pause-control');const links=await page.evaluate(()=>window.__chiron.connections());assert.equal(links.length,16);assert(links.every(x=>Math.max(x.bigEndResidual,x.smallEndResidual)<1e-4));report.renderedConnections=links;for(const degrees of [0,90,180,270]){await page.locator('#phase-degrees').fill(String(degrees));await page.locator('#phase-degrees').press('Tab');await page.waitForTimeout(300);const ls=await page.evaluate(()=>window.__chiron.connections());assert(ls.every(x=>Math.max(x.bigEndResidual,x.smallEndResidual)<1e-4));await shot('O08-phase-'+degrees);}await shot('O08-engine');await page.waitForTimeout(800);const b=await snap();if(b.state.engine==='paused'){const c=b.state.engineTime;await page.waitForTimeout(500);assert.equal((await snap()).state.engineTime,c);}await click('#crown-toggle');});
await check('O10 regulator, dedicated pause and independent clock',async()=>{await click('#dock [data-do=inspect-tourbillon]');await click('#crown-toggle');await page.locator('#balance-rate').selectOption('0');const a=await snap();await page.waitForTimeout(900);const b=await snap();assert.equal(b.state.balanceTime,a.state.balanceTime);assert(b.state.clockSeconds>a.state.clockSeconds);await shot('O10-tourbillon');await click('#crown-toggle');});
await check('O12 continuous assembly at 0,33,66,100 and reverse',async()=>{await click('#explorer .explore-top [data-do=restore]');await click('#anatomy-toggle');for(const n of [0,33,66,100,66,33,0]){await page.locator('#explode').focus();await page.keyboard.press('Home');for(let k=0;k<n;k++)await page.keyboard.press('ArrowRight');await page.waitForTimeout(150);assert(Math.abs((await snap()).state.explodeTarget-n/100)<1e-6);if([0,33,66,100].includes(n)&&!report.shots.some(x=>x.id===`O12-${n}`))await shot(`O12-${n}`);}await click('#anatomy-toggle');});
await check('O16 independent reserves, real time setting, empty start',async()=>{await click('#crown-toggle');await click('#crown-panel [data-do=exhaust]');const a=await snap();await click('#dock [data-do=start]');assert.equal((await snap()).state.engine,'exhausted');await click('#crown-panel [data-do=windEngine]');const b=await snap();assert.equal(b.state.engineEnergy,1);assert(Math.abs(b.state.clockEnergy-a.state.clockEnergy)<.01);await page.locator('#set-time').fill('03:30');await click('#set-time-apply');assert(Math.abs((await snap()).state.clockSeconds-12600)<5);await shot('O16-crowns');await click('#crown-toggle');});
await check('O21 keyboard, mouse drag and wheel camera ownership',async()=>{await click('[data-view=front]');await canvasFocus();const a=await snap();await page.keyboard.press('ArrowRight');await page.keyboard.press('+');const box=await page.locator('#watch-canvas').boundingBox();await page.mouse.move(box.x+box.width*.52,box.y+box.height*.5);await page.mouse.down();await page.mouse.move(box.x+box.width*.60,box.y+box.height*.58,{steps:8});await page.mouse.up();await page.mouse.wheel(0,-70);await page.waitForTimeout(500);const b=await snap();assert.notDeepEqual(a.camera.position,b.camera.position);await page.keyboard.press('r');assert.equal((await snap()).state.selection,'all');});
await check('O22 seeded 100 ordinary-button state transitions',async()=>{if(quick)throw new Error('NOT_EXECUTED in quick diagnostic');await click('#crown-toggle');let seed=240911;const ops=['#dock [data-do=start]','#pause-control','#crystal-control','[data-view=front]','[data-view=back]','#crown-panel [data-do=windClock]','#crown-panel [data-do=windEngine]','#explorer .explore-top [data-do=restore]'];report.random={seed,operations:[]};for(let i=0;i<100;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const q=ops[seed%ops.length];report.random.operations.push(q);await click(q);const s=await snap();assert(s.state.engineEnergy>=0&&s.state.engineEnergy<=3);assert.equal(s.runtime.initializations,1);}await click('#crown-toggle');await click('#explorer .explore-top [data-do=restore]');assert.equal((await snap()).state.selection,'all');});
await check('O13/O30 50 real UI explode/restore cycles, resource stability',async()=>{if(quick)throw new Error('NOT_EXECUTED in quick diagnostic');const a=await snap();await click('#anatomy-toggle');for(let i=0;i<50;i++){await page.locator('#explode').focus();await page.keyboard.press('End');await page.waitForFunction(()=>window.__chiron.snapshot().state.explode===1);await click('#anatomy-panel [data-do=restore]');await page.waitForFunction(()=>window.__chiron.snapshot().state.explode===0);}await page.waitForTimeout(350);const b=await snap();assert(b.assemblyError.position<5.78e-5);assert(b.assemblyError.rotationDegrees<.01);assert.equal(a.renderer.memory.geometries,b.renderer.memory.geometries);assert.equal(a.runtime.initializations,b.runtime.initializations);report.stability={before:a.renderer,after:b.renderer,assemblyError:b.assemblyError};await click('#anatomy-toggle');});
await check('O20 exit restores reading; all chapter content accessible',async()=>{await click('#explorer [data-do=exit]');assert.equal((await snap()).state.mode,'story');for(const id of ['mechanical-pulse','suspended-precision','sapphire-revealed','anatomy','explore-chapter','the-record']){await page.locator('#'+id).scrollIntoViewIfNeeded();await page.waitForTimeout(300);if(id==='the-record'||id==='suspended-precision')await shot('O18-'+id);}assert.equal(await page.locator('.record .specifications dd').count(),8);});
await check('O23 mobile portrait/landscape: viewport emulation only',async()=>{for(const vp of [{width:390,height:844},{width:844,height:390},{width:360,height:800}]){await page.setViewportSize(vp);await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await page.waitForTimeout(350);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await shot(`O23-${vp.width}x${vp.height}`);await click('#the-object [data-do=explore]');assert(await page.locator('[data-do=exit]').isVisible());await shot(`O23-explore-${vp.width}`);await click('#explorer [data-do=exit]');}});
await check('Editable asset export from actual restored model',async()=>{await page.setViewportSize(small?{width:1100,height:800}:{width:1920,height:1080});await click('#the-object [data-do=explore]');await click('#explorer .explore-top [data-do=restore]');await page.waitForTimeout(300);const chunks=await page.evaluate(async()=>{const b=new Uint8Array(await window.__chiron.exportGLB());const out=[];for(let i=0;i<b.length;i+=32768)out.push(btoa(String.fromCharCode(...b.subarray(i,i+32768))));return out;});const glb=Buffer.concat(chunks.map(s=>Buffer.from(s,'base64')));fs.mkdirSync('assets',{recursive:true});fs.writeFileSync('assets/chiron-clear-r02.glb',glb);report.asset={bytes:glb.length,sha256:crypto.createHash('sha256').update(glb).digest('hex'),pose:(await snap()).state};fs.writeFileSync('assets/asset-register.json',JSON.stringify(await page.evaluate(()=>window.__chiron.passport()),null,2));});
report.final=await snap();
}catch(e){report.errors.push(e.stack);save();console.error(e);}finally{
report.finished=new Date().toISOString();report.allExecutedChecksPass=report.checks.every(x=>x.status==='PASS')&&report.errors.length===0;save();await context.close();await browser.close();server?.kill();
}
async function canvasFocus(){await page.locator('#watch-canvas').focus();}
console.log(JSON.stringify({checks:report.checks,errors:report.errors},null,2));
// Test success only describes this suite. It never awards Q3 or the nine contract gates.
if(!report.allExecutedChecksPass&&!quick)process.exitCode=1;
