import {REVISION} from '../version.mjs';
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {gzipSync} from 'node:zlib';import {build} from 'esbuild';import {PISTONS,SPEC} from '../mechanics.mjs';
fs.mkdirSync('dist',{recursive:true});
const result=await build({entryPoints:['main.mjs'],bundle:true,loader:{'.hdr':'binary'},minify:true,format:'iife',outfile:'dist/app.js',metafile:true,legalComments:'eof',target:['es2022']});
const html=fs.readFileSync('index.html','utf8'),css=fs.readFileSync('style.css','utf8');
fs.writeFileSync('dist/index.html',html);fs.writeFileSync('dist/style.css',css);
const parameters=JSON.stringify({revision:REVISION,spec:SPEC,pistons:PISTONS});fs.writeFileSync('dist/mechanism.json',parameters);
const js=fs.readFileSync('dist/app.js','utf8');
const single=html.replace('<link rel="stylesheet" href="./style.css">',()=>`<style>${css}</style>`).replace('<script defer src="./app.js"></script>','').replace('</body>',()=>`<script>window.__INLINE_MECHANISM__=${parameters};</script><script>${js.replace(/<\/script/gi,'<\\/script')}</script></body>`);
fs.writeFileSync('dist/Chiron-Sapphire-R02.html',single);
fs.writeFileSync('dist/Chiron-Sapphire-R04.html',single);
fs.writeFileSync('dist/Chiron-Sapphire-R05.html',single);
fs.writeFileSync('dist/Chiron-Sapphire-R06.html',single);
fs.writeFileSync(`dist/Chiron-Sapphire-${REVISION}.html`,single);
const inputs=Object.keys(result.metafile.inputs).filter(p=>!p.includes('node_modules/')).sort();
const shas=Object.fromEntries([...inputs,'index.html','style.css','package-lock.json','tools/build.mjs'].map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')]));
const files=Object.fromEntries(['index.html','style.css','app.js','mechanism.json'].map(p=>{const b=fs.readFileSync('dist/'+p);return[p,{bytes:b.length,gzipBytes:gzipSync(b).length,sha256:crypto.createHash('sha256').update(b).digest('hex')}];}));
const buildHash=crypto.createHash('sha256').update(JSON.stringify(shas)).digest('hex');
const manifest={revision:REVISION,buildHash,inputs:shas,files,network:'No third-party runtime requests',fonts:'Installed system fonts only; no font files distributed'};
fs.writeFileSync('dist/build-manifest.json',JSON.stringify(manifest,null,2));fs.mkdirSync('evidence/R05',{recursive:true});fs.writeFileSync('evidence/R05/BUILD-MANIFEST.json',JSON.stringify(manifest,null,2));fs.mkdirSync(`evidence/${REVISION}`,{recursive:true});fs.writeFileSync(`evidence/${REVISION}/BUILD-MANIFEST.json`,JSON.stringify(manifest,null,2));console.log(JSON.stringify(manifest,null,2));
