/** Adversarial browser health / touch checks. Fault injection changes transport or browser capability, not the application state. */
import {chromium} from '@playwright/test';import fs from 'node:fs';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';
const root='evidence/R05/health';fs.mkdirSync(root,{recursive:true});const local=process.env.CHIRON_LOCAL_DOCUMENT==='1';
const manifest=JSON.parse(fs.readFileSync('dist/build-manifest.json')),report={buildHash:manifest.buildHash,transport:local?'SANDBOX_DOCUMENT_INJECTION':'HTTP',assurance:'actual Chromium; software renderer; simulated touch, not phone hardware',checks:[],errors:[],snapshots:[]};
const save=()=>fs.writeFileSync(root+'/health-report.json',JSON.stringify(report,null,2));
let server;if(!local){server=spawn(process.execPath,['tools/serve.mjs'],{stdio:'ignore'});await new Promise(r=>setTimeout(r,800));}
const opts={headless:false,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']};if(process.env.CHROMIUM_PATH)opts.executablePath=process.env.CHROMIUM_PATH;
const browser=await chromium.launch(opts);const html=fs.readFileSync('dist/Chiron-Sapphire-R02.html','utf8');
async function context(extra={}){const c=await browser.newContext({viewport:{width:1100,height:800},deviceScaleFactor:1,recordVideo:{dir:root+'/video',size:{width:1100,height:800}},...extra});c.on('page',p=>p.on('pageerror',e=>report.errors.push(e.message)));return c;}
async function load(p){if(local)await p.setContent(html);else await p.goto('http://127.0.0.1:4173');}
async function ready(p){await p.waitForFunction(()=>window.__chiron?.snapshot().state.ready,{},{timeout:90000});}
const snap=p=>p.evaluate(()=>window.__chiron.snapshot());
async function shot(p,name){await p.screenshot({path:`${root}/${name}.png`});report.snapshots.push({name,snapshot:await snap(p)});save();}
async function test(name,fn){console.log('BEGIN',name);const existing=new Set(browser.contexts());try{await fn();report.checks.push({name,status:'PASS'});}catch(e){report.checks.push({name,status:'FAIL',error:e.stack});console.error(e.message);}finally{for(const c of browser.contexts())if(!existing.has(c))await c.close();}save();}
try{
 await test('O27 disabled WebGL retains honest complete HTML document',async()=>{const c=await context(),p=await c.newPage();await p.evaluate(()=>{const native=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(t,...a){return /webgl/i.test(t)?null:native.call(this,t,...a);};});if(!local)await p.addInitScript(()=>{const native=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(t,...a){return /webgl/i.test(t)?null:native.call(this,t,...a);};});await load(p);await p.locator('#fallback').waitFor({state:'visible'});assert.equal(await p.locator('.chapter').count(),7);assert.equal(await p.locator('.specifications dd').count(),8);assert.equal((await snap(p)).state.ready,false);await shot(p,'O27-no-webgl');await p.locator('#fallback a').click();assert(await p.locator('#the-record').isVisible());await c.close();});
 await test('O26 parameter request fails, retries, one actual initialization',async()=>{const c=await context(),p=await c.newPage();let failing=true,requests=0;await p.route('**/mechanism.json',route=>{requests++;return route.fulfill({status:failing?503:200,contentType:'application/json',body:failing?'{}':fs.readFileSync('dist/mechanism.json','utf8')});});if(local){const bare=html.replace(/<script>window\.__INLINE_MECHANISM__=[\s\S]*?<\/script>/,'').replace('<head>','<head><base href="https://chiron-fixture.invalid/">');await p.setContent(bare);}else await load(p);await p.locator('#fallback').waitFor({state:'visible'});assert((await p.locator('#failure-reason').textContent()).includes('503'));assert.equal((await snap(p)).state.ready,false);await shot(p,'O26-resource-failure');failing=false;await p.locator('#retry').click();await ready(p);const s=await snap(p);assert.equal(s.runtime.initializations,1);assert.equal(requests,2);report.resourceRecovery={requests,backend:s.runtime.backend,fixture:local?'virtual origin and route fulfilment; actual unchanged fetch/retry code':'HTTP request interception'};await shot(p,'O26-resource-recovered');await c.close();});
 await test('O26 real WebGL context loss/restore preserves model and state',async()=>{const c=await context(),p=await c.newPage();await load(p);await ready(p);await p.locator('#the-object [data-do=explore]').click();await p.locator('#motion-toggle').click();await p.locator('#dock [data-do=start]').click();await p.locator('#pause-control').click();const a=await snap(p);await p.evaluate(()=>document.querySelector('#watch-canvas').getContext('webgl2').getExtension('WEBGL_lose_context').loseContext());await p.waitForFunction(()=>window.__chiron.snapshot().runtime.contextLosses===1);await shot(p,'O26-context-lost');await p.locator('#retry').click();await p.waitForFunction(()=>window.__chiron.snapshot().runtime.contextRestores===1,{},{timeout:60000});await p.waitForTimeout(500);const b=await snap(p);assert.equal(b.runtime.initializations,1);assert.equal(b.state.engineEnergy,a.state.engineEnergy);assert.equal(b.state.engineTime,a.state.engineTime);assert.equal(b.state.engine,'paused');report.contextRecovery={before:a,after:b};await shot(p,'O26-context-restored');await c.close();});
 await test('O25 real tab hide pauses W16 and does not spawn extra RAF',async()=>{const c=await context(),p=await c.newPage();await load(p);await ready(p);await p.locator('#the-object [data-do=explore]').click();await p.locator('#dock [data-do=start]').click();// Playwright normally forces focus emulation on; disable that testing override to observe real tab visibility.
 const visibilityClient=await c.newCDPSession(p);await visibilityClient.send('Emulation.setFocusEmulationEnabled',{enabled:false});const other=await c.newPage();const otherClient=await c.newCDPSession(other);await otherClient.send('Emulation.setFocusEmulationEnabled',{enabled:false});await other.bringToFront();report.visibilityProbe={watch:await p.evaluate(()=>({hidden:document.hidden,visibility:document.visibilityState})),other:await other.evaluate(()=>({hidden:document.hidden,visibility:document.visibilityState}))};save();await p.waitForFunction(()=>document.hidden,{},{timeout:15000,polling:100});const a=await snap(p);await other.waitForTimeout(1200);const b=await snap(p);assert.equal(b.state.engineTime,a.state.engineTime);assert.equal(b.runtime.rafOutstanding,0);await p.bringToFront();await p.waitForFunction(()=>!document.hidden,{},{polling:100});await p.waitForTimeout(400);const d=await snap(p);assert.equal(d.runtime.initializations,1);assert(d.runtime.rafOutstanding<=1);assert(d.state.engineTime-b.state.engineTime<1.1);report.background={before:a,hidden:b,resumed:d};await c.close();});
 await test('O21 actual touchscreen protocol drag/pinch and keyboard escape',async()=>{const c=await context({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),p=await c.newPage();await load(p);await ready(p);await p.locator('#the-object [data-do=explore]').tap();await p.locator('#motion-toggle').tap();const a=await snap(p),b=await p.locator('#watch-canvas').boundingBox(),client=await c.newCDPSession(p);const x=b.x+b.width*.5,y=b.y+b.height*.5;await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y,id:1}]});for(let i=1;i<=10;i++)await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+i*5,y:y+i*2,id:1}]});await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(350);const d=await snap(p);assert.notDeepEqual(a.camera.position,d.camera.position);await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:x-30,y,id:1},{x:x+30,y,id:2}]});for(let i=1;i<=7;i++)await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x-30-i*4,y,id:1},{x:x+30+i*4,y,id:2}]});await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await p.waitForTimeout(300);const e=await snap(p);assert.notDeepEqual(d.camera.position,e.camera.position);await shot(p,'O21-touch');await p.locator('#watch-canvas').focus();await p.keyboard.press('Escape');assert.equal((await snap(p)).state.mode,'story');assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));report.touch={before:a,afterDrag:d,afterPinch:e};await c.close();});
 await test('O11 bounded suspension begins, returns, model remains connected',async()=>{const c=await context(),p=await c.newPage();await load(p);await ready(p);await p.locator('#the-object [data-do=explore]').click();await p.locator('[data-view=front]').click();await p.locator('#crown-toggle').click();await p.locator('#crown-panel [data-do=suspension]').click();const states=[];for(let i=0;i<18;i++){await p.waitForTimeout(200);states.push(await snap(p));}assert(states[0].state.suspensionTime<3);assert(states.at(-1).state.suspensionTime>3);assert(states.every(s=>s.runtime.initializations===1));const links=await p.evaluate(()=>window.__chiron.connections());assert(links.every(x=>Math.max(x.bigEndResidual,x.smallEndResidual)<1e-4));report.suspension={trace:states,note:'Animation state + real video; full world-space spring attachment/max-clearance tolerance not awarded by this assertion.'};await shot(p,'O11-suspension-rest');await c.close();});
}catch(e){report.errors.push(e.stack);}finally{report.finished=new Date().toISOString();save();await browser.close();server?.kill();}
report.allExecutedChecksPass=report.errors.length===0&&report.checks.every(c=>c.status==='PASS');save();console.log(report.checks);if(!report.allExecutedChecksPass)process.exitCode=1;
