import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createState,action,tick,handAngles,PISTONS,solvePiston,verifyKinematics,SPEC,TAU} from '../mechanics.mjs';
test('721 phases × all sixteen connected sliders',()=>{const r=verifyKinematics();assert.equal(r.outputs,16);assert.ok(r.pass);fs.mkdirSync('evidence/R02',{recursive:true});fs.writeFileSync('evidence/R02/O09-kinematics.json',JSON.stringify({spec:SPEC,pistons:PISTONS,result:r},null,2));});
test('eight shared crankpins; periodic continuous branch',()=>{assert.equal(new Set(PISTONS.map(x=>x.sharedPin)).size,8);for(const p of PISTONS)assert.ok(Math.abs(solvePiston(p,0).s-solvePiston(p,TAU).s)<1e-12);});
test('one START consumes once; pause is frozen; clock remains independent',()=>{const s=createState();s.ready=true;action(s,'start');for(let i=0;i<30;i++)action(s,'start');assert.equal(s.starts,1);assert.equal(s.engineEnergy,2);tick(s,.1);action(s,'pause');const theta=s.engineTheta,t=s.clockSeconds;tick(s,.1);assert.equal(s.engineTheta,theta);assert.ok(s.clockSeconds>t);});
test('slow motion extends wall time, not simulated cycle duration',()=>{const s=createState();s.ready=true;s.engineRate=.25;action(s,'start');for(let i=0;i<600;i++)tick(s,.1);assert.ok(Math.abs(s.engineTime-15)<1e-8);assert.equal(s.engine,'idle');});
test('independent winding, empty start, and real hand setting',()=>{const s=createState();s.ready=true;action(s,'exhaust');action(s,'start');assert.equal(s.starts,0);const c=s.clockEnergy;action(s,'windEngine');assert.equal(s.clockEnergy,c);assert.equal(s.engineEnergy,1);action(s,'windClock');assert.equal(s.engineEnergy,1);action(s,'setTime','03:30');const a=handAngles(s.clockSeconds);assert.ok(Math.abs(a.minute+Math.PI)<1e-12);assert.ok(Math.abs(a.hour+7*Math.PI/12)<1e-12);});
test('50 interrupted disassembly cycles return exactly without erasing energy',()=>{const s=createState();s.ready=true;action(s,'start');for(let i=0;i<50;i++){action(s,'explode',.33);tick(s,.05);action(s,'explode',1);tick(s,.1);action(s,'restore');for(let j=0;j<50;j++)tick(s,.05);assert.equal(s.explode,0);assert.equal(s.selection,'all');}assert.equal(s.engineEnergy,2);});
test('hidden/tab long interval does not jump mechanical phase',()=>{const s=createState();s.ready=true;action(s,'start');tick(s,600);assert.equal(s.engineTime,0);});

test('emptying W16 never replenishes or depletes the independent clock store',()=>{for(const reserve of [0,.37,1]){const s=createState();s.ready=true;s.clockEnergy=reserve;const seconds=s.clockSeconds;action(s,'exhaust');assert.equal(s.engineEnergy,0);assert.equal(s.clockEnergy,reserve);assert.equal(s.clockSeconds,seconds);action(s,'windEngine');assert.equal(s.clockEnergy,reserve);}});
