/** Three actual scenes × three 30-second samples, no video capture during measurement. No hardware-equivalence claim. */
import {chromium} from '@playwright/test';import fs from 'node:fs';import {spawn} from 'node:child_process';
const out='evidence/R02/performance';fs.mkdirSync(out,{recursive:true});const local=process.env.CHIRON_LOCAL_DOCUMENT==='1';const report={buildHash:JSON.parse(fs.readFileSync('dist/build-manifest.json')).buildHash,viewport:{width:1920,height:1080},dpr:1,secondsPerSample:30,repeats:3,measurement:'actual requestAnimationFrame/render cadence, not instrumented physical display scanout',runs:[],errors:[]};const save=()=>fs.writeFileSync(out+'/performance.json',JSON.stringify(report,null,2));
let server;if(!local){server=spawn(process.execPath,['tools/serve.mjs'],{stdio:'ignore'});await new Promise(r=>setTimeout(r,800));}
const opts={headless:false,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']};if(process.env.CHROMIUM_PATH)opts.executablePath=process.env.CHROMIUM_PATH;else if(fs.existsSync('/usr/bin/chromium'))opts.executablePath='/usr/bin/chromium';const browser=await chromium.launch(opts),context=await browser.newContext({viewport:report.viewport,deviceScaleFactor:1}),p=await context.newPage();p.setDefaultTimeout(60000);
const snap=()=>p.evaluate(()=>({capturedAt:performance.now(),...window.__chiron.snapshot()}));
const percentile=(a,q)=>{const x=[...a].sort((a,b)=>a-b);return x.length?x[Math.min(x.length-1,Math.floor((x.length-1)*q))]:null;};
try{if(local)await p.setContent(fs.readFileSync('dist/Chiron-Sapphire-R02.html','utf8'));else await p.goto('http://127.0.0.1:4173');await p.waitForFunction(()=>window.__chiron?.snapshot().state.ready,{},{timeout:90000});report.backend=(await snap()).runtime.backend;report.softwareRenderer=/swiftshader|llvmpipe|software/i.test(report.backend.renderer);report.transport=local?'SANDBOX_DOCUMENT_INJECTION':'HTTP';await p.locator('#the-object [data-do=explore]').click();
 for(const scene of ['whole-watch-orbit','W16-running','disassembled']){
  await p.locator('#explorer .explore-top [data-do=restore]').click();
  if(scene==='W16-running'){await p.locator('#dock [data-do=inspect-engine]').click();await p.locator('#crown-toggle').click();await p.locator('#engine-rate').selectOption('0.1');await p.locator('#crown-panel [data-do=windEngine]').click();await p.locator('#dock [data-do=start]').click();await p.locator('#crown-toggle').click();}
  if(scene==='disassembled'){await p.locator('#anatomy-toggle').click();await p.locator('#explode').focus();await p.keyboard.press('End');await p.waitForFunction(()=>window.__chiron.snapshot().state.explode===1);await p.locator('#anatomy-toggle').click();}
  await p.waitForTimeout(5000);await p.screenshot({path:`${out}/${scene}.png`});
  for(let repeat=1;repeat<=3;repeat++){const a=await snap();let timer=null;if(scene==='whole-watch-orbit'){await p.locator('#watch-canvas').focus();timer=setInterval(()=>p.keyboard.press('ArrowRight').catch(()=>{}),400);}await p.waitForTimeout(30000);if(timer)clearInterval(timer);const b=await snap(),n=b.totalFrames-a.totalFrames,intervals=b.renderIntervals.slice(-Math.min(n,b.renderIntervals.length)),median=percentile(intervals,.5),p95=percentile(intervals,.95);report.runs.push({scene,repeat,elapsedMs:b.capturedAt-a.capturedAt,renderedFrames:n,intervalCount:intervals.length,medianFps:median?1000/median:null,p95Ms:p95,projectBudgetReached:median!==null&&1000/median>=55&&p95<=25,rawFrameIntervals:intervals,stateStart:a.state,stateEnd:b.state,renderer:b.renderer,camera:b.camera});save();console.log(scene,repeat,report.runs.at(-1).medianFps,p95);}
 }
}catch(e){report.errors.push(e.stack);}finally{report.finished=new Date().toISOString();report.physicalGpuGate=report.softwareRenderer?'NOT_VERIFIED: software backend cannot certify a physical GPU or phone':'Review measured device and nine contract gates separately';save();await context.close();await browser.close();server?.kill();}
